//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra_produto
    {
        public int compra_id { get; set; }
        public int lote_id { get; set; }
        public int quantidade { get; set; }
        public float valorUnitario { get; set; }
    
        public virtual compra compra { get; set; }
        public virtual lote lote { get; set; }
    }
}
