//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public compra()
        {
            this.compra_produto = new HashSet<compra_produto>();
        }
    
        public int id { get; set; }
        public int fornecedor_id { get; set; }
        public System.DateTime dataDeEntrega { get; set; }
        public float valorTotal { get; set; }
    
        public virtual fornecedor fornecedor { get; set; }
        public virtual ICollection<compra_produto> compra_produto { get; set; }
    }
}
