//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class controlsystemEntities : DbContext
    {
        public controlsystemEntities()
            : base("name=controlsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<devolucao> devolucao { get; set; }
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<estoque> estoque { get; set; }
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<lote> lote { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<venda> venda { get; set; }
        public virtual DbSet<venda_produto> venda_produto { get; set; }
        public virtual DbSet<compra_produto> compra_produto { get; set; }
        public virtual DbSet<fornecedor_produto> fornecedor_produto { get; set; }
        public virtual DbSet<estados> estados { get; set; }
    }
}
