//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolucao
    {
        public int id { get; set; }
        public bool retornaEstoque { get; set; }
        public string motivo { get; set; }
        public int venda_produto_id { get; set; }
    
        public virtual venda_produto venda_produto { get; set; }
    }
}
