//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class devolução
    {
        public int idDevolução { get; set; }
        public int Item_Venda_notaFiscalVenda { get; set; }
        public int Estoque_codProduto { get; set; }
        public int lote { get; set; }
        public int quantidade { get; set; }
        public bool retornaEstoque { get; set; }
        public string motivo { get; set; }
    }
}
