//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public endereco()
        {
            this.cliente = new HashSet<cliente>();
            this.fornecedor = new HashSet<fornecedor>();
            this.funcionario = new HashSet<funcionario>();
        }
    
        public int id { get; set; }
        public string endereco1 { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public int cep { get; set; }
        public string cidade { get; set; }
        public string UF { get; set; }
    
        public virtual ICollection<cliente> cliente { get; set; }
        public virtual ICollection<fornecedor> fornecedor { get; set; }
        public virtual ICollection<funcionario> funcionario { get; set; }
    }
}
