//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class estoque
    {
        public int codProduto { get; set; }
        public int codLoja { get; set; }
        public int Lote_Lote { get; set; }
        public int Lote_codProduto { get; set; }
        public int precoUnitVenda { get; set; }
        public int quantidade { get; set; }
        public string tipoProduto { get; set; }
        public int estoqueMaximo { get; set; }
        public int estoqueMinimo { get; set; }
        public string status { get; set; }
    
        public virtual lote lote { get; set; }
    }
}
