//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor
    {
        public int cnpj { get; set; }
        public int Compra_numCompra { get; set; }
        public string razaoSocial { get; set; }
        public string nomeFantasia { get; set; }
        public string endereco { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public int cep { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public decimal telefone { get; set; }
        public string email { get; set; }
        public System.DateTime dataDeCadastramento { get; set; }
        public string contato { get; set; }
        public decimal telefoneContato { get; set; }
        public string emailContato { get; set; }
        public string status { get; set; }
    }
}
