//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor_produto
    {
        public int cnpj { get; set; }
        public int Estoque_codProduto { get; set; }
        public int preco { get; set; }
        public System.DateTime dataCotacao { get; set; }
        public string status { get; set; }
    }
}
