//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedor
    {
        public fornecedor()
        {
            this.compra = new HashSet<compra>();
            this.fornecedor_produto = new HashSet<fornecedor_produto>();
        }
    
        public int id { get; set; }
        public string cnpj { get; set; }
        public string razaoSocial { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public System.DateTime dataDeCadastramento { get; set; }
        public string contato { get; set; }
        public string telefoneContato { get; set; }
        public string emailContato { get; set; }
        public Nullable<int> status { get; set; }
        public int endereco_id { get; set; }
    
        public virtual ICollection<compra> compra { get; set; }
        public virtual endereco endereco { get; set; }
        public virtual ICollection<fornecedor_produto> fornecedor_produto { get; set; }
    }
}
