//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionário
    {
        public funcionário()
        {
            this.venda = new HashSet<venda>();
        }
    
        public int matriculaFuncionário { get; set; }
        public string nome { get; set; }
        public string endereco { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public int cep { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public decimal telefone { get; set; }
        public string email { get; set; }
        public System.DateTime dataDeAdmissao { get; set; }
        public System.DateTime dataDeDemissao { get; set; }
        public string perfilDeAcesso { get; set; }
        public string cargo { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<venda> venda { get; set; }
    }
}
