//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_compra
    {
        public int codProduto { get; set; }
        public int numCompra { get; set; }
        public string qtdCadaProduto { get; set; }
        public int valorItem { get; set; }
    }
}
