//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        public lote()
        {
            this.estoque = new HashSet<estoque>();
        }
    
        public int Lote1 { get; set; }
        public int codProduto { get; set; }
        public System.DateTime dataDeValidade { get; set; }
        public System.DateTime dataDeFabricacao { get; set; }
        public int quantidade { get; set; }
    
        public virtual ICollection<estoque> estoque { get; set; }
    }
}
