//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class lote
    {
        public lote()
        {
            this.estoque = new HashSet<estoque>();
            this.compra_produto = new HashSet<compra_produto>();
            this.venda_produto = new HashSet<venda_produto>();
        }
    
        public int id { get; set; }
        public System.DateTime dataValidade { get; set; }
        public System.DateTime dataFabricacao { get; set; }
        public string identificador { get; set; }
        public int produto_id { get; set; }
    
        public virtual ICollection<estoque> estoque { get; set; }
        public virtual ICollection<compra_produto> compra_produto { get; set; }
        public virtual produto produto { get; set; }
        public virtual ICollection<venda_produto> venda_produto { get; set; }
    }
}
