//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public produto()
        {
            this.lote = new HashSet<lote>();
            this.fornecedor_produto = new HashSet<fornecedor_produto>();
        }
    
        public int id { get; set; }
        public string desc { get; set; }
        public float valorUnitario { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<lote> lote { get; set; }
        public virtual ICollection<fornecedor_produto> fornecedor_produto { get; set; }
    }
}
