//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda_produto
    {
        public venda_produto()
        {
            this.devolucao = new HashSet<devolucao>();
        }
    
        public int id { get; set; }
        public int quantidade { get; set; }
        public int valorUnitario { get; set; }
        public int venda_id { get; set; }
        public int lote_id { get; set; }
    
        public virtual ICollection<devolucao> devolucao { get; set; }
        public virtual lote lote { get; set; }
        public virtual venda venda { get; set; }
    }
}
