//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        public int notaFiscalVenda { get; set; }
        public int Cliente_idCliente { get; set; }
        public int Funcionário_matriculaFuncionário { get; set; }
        public System.DateTime dataVenda { get; set; }
        public decimal valorTotal { get; set; }
        public string desconto { get; set; }
        public decimal valorTotalComDesconto { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual funcionário funcionário { get; set; }
    }
}
