//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class venda
    {
        public venda()
        {
            this.venda_produto = new HashSet<venda_produto>();
        }
    
        public int id { get; set; }
        public int notaFiscal { get; set; }
        public System.DateTime dataDaVenda { get; set; }
        public float valorTotal { get; set; }
        public Nullable<float> desconto { get; set; }
        public float valorTotalComDesconto { get; set; }
        public int funcionario_id { get; set; }
        public int cliente_id { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual ICollection<venda_produto> venda_produto { get; set; }
    }
}
